blank_issues_enabled: false
contact_links:
  - name: 📖 Marlin2ForPipetBot Documentation
    url: https://github.com/DerAndere1/Marlin/wiki
    about: Documentation on installing and using Marlin2ForPipetBot.
  - name: 📖 Marlin2ForPipetBot README
    url: https://github.com/DerAndere1/Marlin/blob/Marlin2ForPipetBot/README.md
    about: Frequently updated brief documentation on installing and using Marlin2ForPipetBot.
  - name: 📖 Marlin Documentation
    url: https://marlinfw.org/
    about: Lots of documentation on installing and using Marlin.
  - name: 👤 MarlinFirmware Facebook group
    url: https://www.facebook.com/groups/1049718498464482
    about: Please ask and answer questions here.
  - name: 🕹 Marlin on Discord
    url: https://discord.com/servers/marlin-firmware-461605380783472640
    about: Join the Discord server for support and discussion.
  - name: 🔗 Marlin Discussion Forum
    url: https://reprap.org/forum/list.php?415
    about: A searchable web forum hosted by RepRap dot org.
  - name: 📺 Marlin Videos on YouTube
    url: https://www.youtube.com/results?search_query=marlin+firmware
    about: Tutorials and more from Marlin users all around the world. Great for new users!
  - name: 💸 Want to donate?
    url: https://www.paypal.com/donate/?hosted_button_id=TNGG65GVA9UHE
    about: Support Marlin2ForPipetBot development financially!
